#!/bin/dash

directory=".shrug"
current_path=`pwd`

# Check if directory exits
if [ ! -d "$directory" ]; then

    echo "shrug-add: error: no .shrug directory containing shrug repository exists"
    exit 1
fi

for file in "$@"; 
do
	if [ ! -f "$file" ]; then

        # check if file is in repository
        if [ ! -f "$current_path/$directory/$file" ]; then
            echo "shrug-add: error: can not open '$file'"
            exit 1
            
        fi
    fi
done 


directory="index"

new_path="$current_path/.shrug"

# Index folder path
index_dir="$new_path/$directory"
del_flag=1

# Checking if Index exists
if [ ! -d "$index_dir" ]; then
    mkdir $index_dir
    del_flag=0
fi



# Commit count
commit=0
while true; do
    # Commit index folder
	subD=$directory$commit

    # Commit index path
    index_path="$new_path/$subD"

    # Checking if commit index folder exists
    if [ ! -d $index_path ]; then

        # Folder for new commit
        mkdir $index_path
        break
    fi
    commit=$((commit + 1))
done



cd $current_path
for file in "$@"; 
do	
    if [ ! -f "$current_path/$file" ]; then
        
        rm "$index_dir/$file"
        continue
    fi
	case $file in
        *[![:alnum:]_.-]*)
            ;;
        *)
        # Copy files into commit folder
        cp $file $index_path
        # Copy files into Index folder
        cp $file $index_dir        
    esac

done
