#!/bin/dash

index_num=`echo $1 | cut -d':' -f1`
file_name=`echo $1 | cut -d':' -f2`

cd .shrug

# If no number in argument -> show index file
if [ -z "$index_num" ]; then
    cd index
    if [ -f "$file_name" ]; then
        cat $file_name
        exit 1
    else  
        echo "shrug-show: error: '$file_name' not found in index"
        exit 1
    fi
       
fi

# if commit number given, check if commit exists
if [ ! -d "index$index_num" ]; then
    
    echo "shrug-show: error: unknown commit '$index_num'"
    exit 1
else 
    # Commit exists, show file
    cd index$index_num
    if [ -f "$file_name" ]; then
        cat $file_name
        exit 1
    fi
fi 

# Commit exists, but file not in commmit so check Index
cd ..
if [ -f "$file_name" ]; then
    cat $file_name
        exit 1
else 
    echo "shrug-show: error: '$file_name' not found in commit $index_num"
fi

exit 1









