#!/bin/dash

directory=".shrug"

if [ ! -d "$directory" ]; then
    
    mkdir ./$directory
    echo "Initialized empty shrug repository in .shrug"
else 
    echo "shrug-init: error: .shrug already exists"
fi 

exit 1
