#!/bin/dash

# directory path
dir_path=`pwd`

cd .shrug
log="log.txt"

# Commit number
num=0

num=`ls -l | grep "^d" | wc -l`
num=`echo $num | sed 's/ *$//g'`

if [ "$#" -eq 3 ]; then
    message=$3
    indnum=$((num -1))
    num=`wc -l <$log`
    num=`echo $num | sed 's/ *$//g'`
    echo "$num $message" >>$log

else 
    message=$2
    num=$((num -2))
    echo "$num $message" >>$log 
fi

repo_path=`pwd`
index_path="$repo_path/index"

# Add current directory files into index before commit
if [ "$#" -eq 3 ]; then 

    cd $dir_path
    for file in *; do 
        if [ -f "$index_path/$file" ]; then

            cp $file "$index_path/$file"
        fi
    done
    cd .shrug
    # Make new commit folder
    mkdir "$index_path$indnum"

    cd $index_path

    for file in *; do 
        
        cp $file "$index_path$num/$file"

    done
fi

# same file counter
diff_c=0

# number of files commiting counter
num_of_file=0

cd $index_path
for file in *;
do
    # Checking if committing files have no change
    if [ "$#" -eq 2 ]; then
        
        num_of_file=$((num_of_file + 1))
        file_path="$index_path/$file"
        prev_path="$repo_path/$file"

        if [ -f "$prev_path" ]; then 

            if cmp -s $prev_path $file_path; then
    
                diff_c=$((diff_c + 1))

            fi
        fi
    fi
    cp $file ..
done




if [ "$diff_c" -eq "$num_of_file" ] ; then
    
    if [ "$num_of_file" -ne 0 ]; then
        echo "nothing to commit"
    else 
        echo "Committed as commit $num "
    fi    
else 
    echo "Committed as commit $num "
fi 
exit 1
 




