#!/bin/dash

directory=".shrug"

# Check if directory exists
if [ ! -d "$directory" ]; then    
    mkdir ./$directory
    echo "Initialized empty shrug repository in .shrug"
else 
    # Direcyory exists, print error
    echo "shrug-init: error: .shrug already exists"
fi 

exit 1
