#!/bin/dash

directory=".shrug"

if [ ! -d "$directory" ]; then

    echo "shrug-add: error: no .shrug directory containing shrug repository exists"
    exit 1
fi

for file in "$@"; 
do
	if [ ! -f "$file" ]; then
        echo "shrug-add: error: can not open '$file'"
        exit 1
    fi
done 


directory="index"
current_path=`pwd`
new_path="$current_path/.shrug"

# Index folder path
index_dir="$new_path/$directory"

# Checking if Index exitst
if [ ! -d "$index_dir" ]; then
    mkdir $index_dir
fi

# Commit count
commit=0
while true; do
    # Commit index folder
	subD=$directory$commit

    # Commit index path
    index_path="$new_path/$subD"

    # Checking if commit index folder exists
    if [ ! -d $index_path ]; then

        # Folder for new commit
        mkdir $index_path
        break
    fi
    commit=$((commit + 1))
done

# emptying index folder
# rm "$index_dir/*"


for file in "$@"; 
do			
	case $input in
        *[![:alnum:]_.-]*)
            ;;
        *)
        # Copy files into commit folder
        cp $file $index_path
        # Copy files into Index folder
        cp $file $index_dir        
    esac

done
